
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Feb 04 15:34:19 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 34;
  public static final int LBRACKET = 8;
  public static final int CHAR = 49;
  public static final int CONST = 10;
  public static final int NAMESPACE = 5;
  public static final int PERIOD = 16;
  public static final int GEQUAL = 28;
  public static final int CONTINUE = 39;
  public static final int LPAREN = 14;
  public static final int GREATER = 27;
  public static final int SEMI = 6;
  public static final int FOR = 36;
  public static final int LESS = 29;
  public static final int MINUS = 32;
  public static final int STATIC = 13;
  public static final int RPAREN = 15;
  public static final int AND = 19;
  public static final int OR = 20;
  public static final int BOOL = 50;
  public static final int COMMA = 7;
  public static final int CLASS = 11;
  public static final int INC = 21;
  public static final int PLUS = 31;
  public static final int MULTIPLY = 33;
  public static final int IF = 41;
  public static final int ASSIGN = 24;
  public static final int THIS = 46;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int RBRACKET = 9;
  public static final int EQUAL = 25;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int NUMBER = 47;
  public static final int IDENT = 48;
  public static final int BREAK = 40;
  public static final int VOID = 43;
  public static final int ARROW = 45;
  public static final int COLON = 44;
  public static final int ELSE = 42;
  public static final int LBRACE = 3;
  public static final int READ = 37;
  public static final int LEQUAL = 30;
  public static final int NEQUAL = 26;
  public static final int SCOPE = 17;
  public static final int RBRACE = 4;
  public static final int MODULUS = 35;
  public static final int EXTENDS = 12;
  public static final int PROG = 2;
  public static final int DEC = 22;
  public static final int PRINT = 23;
}

